# -*- coding: utf-8 -*-
"""Project_Number to Words Converter using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QklT3TGQ6D6CqjZgtwT-vFFfqDUywXKA

# Project: Number to Words Converter

💡 Question:

Write a Python program that converts a given number into its word representation.


Each digit of the number should be converted into its corresponding word.
If the input contains characters that are not digits (0-9), replace them with an exclamation mark (!).

📌 Example:

Input:  1234  
Output: One Two Three Four  

Input:  98a7  
Output: Nine Eight ! Seven
"""

phone = input("Phone: ")

digits_mapping = {
    "1" : "One",
    "2" : "Two",
    "3" : "Three",
    "4" : "Four",
    "5" : "Five",
    "6" : "Six",
    "7" : "Seven",
    "8" : "Eight",
    "9" : "Nine",
    "0" : "Zero"
}

output = ""

for ch in phone:
  output += digits_mapping.get(ch, "!") + " "

print(output)

"""## -----------------------------------------------------------------------
## Thank you for using this program!
## Feel free to reach out for collaboration or feedback.
## LinkedIn: https://www.linkedin.com/in/khushi-jhamb/
## Email: 39khushi@gmail.com
##-----------------------------------------------------------------------
"""